import type {
  AdminUser,
  Customer,
  Database,
  Order,
  Product,
  SiteSettings,
} from "./types";

const DAY = 86_400_000;
const NOW = Date.now();
const ago = (days: number, hours = 0) => NOW - days * DAY - hours * 3_600_000;

export const img = (id: string, w = 900) =>
  `https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=${w}&q=72`;

type SeedProduct = Omit<Product, "quantity" | "createdAt" | "updatedAt"> & {
  days: number;
  hours?: number;
};

const seedProducts: SeedProduct[] = [
  {
    id: "p_veste_cuir_marron",
    title: "Veste en cuir véritable — Camel patiné",
    description:
      "Superbe veste en cuir de vachette, coupe droite intemporelle. Trouvée dans une brocante du Vieux-Lyon, la patine naturelle raconte déjà quelques décennies d'histoires. Doublure intérieure d'origine en parfait état, fermeture éclair fonctionnelle.",
    price: 8900,
    compareAtPrice: 14000,
    category: "vetements",
    brand: "Sans marque (atelier français)",
    country: "FR",
    city: "Lyon",
    condition: "Très bon état",
    era: "Années 80",
    size: "L",
    measurements: "Épaules 46 cm · Poitrine 56 cm · Longueur 68 cm · Manches 63 cm",
    material: "100% cuir de vachette, doublure viscose",
    images: [img("1551028719-00167b16eac5"), img("1520975954732-35dd22299614")],
    tags: ["cuir", "vintage", "veste", "français"],
    status: "AVAILABLE",
    featured: true,
    days: 2,
    soldAt: undefined,
  },
  {
    id: "p_blouson_adidas",
    title: "Blouson Adidas vintage — Vert sauge",
    description:
      "Blouson coupe-vent Adidas des années 90, coloris vert sauge devenu introuvable. Acheté dans un vide-grenier de Bavière. Logo brodé d'époque, zips d'origine impeccables.",
    price: 2900,
    category: "vetements",
    brand: "Adidas",
    country: "DE",
    city: "Munich",
    condition: "Très bon état",
    era: "Années 90",
    size: "M",
    measurements: "Épaules 45 cm · Poitrine 54 cm · Longueur 66 cm",
    material: "Nylon technique",
    images: [img("1591047139829-d91aecb6caea"), img("1492707892479-7bc8d5a4ee93")],
    tags: ["adidas", "sport", "oversize"],
    status: "AVAILABLE",
    featured: true,
    days: 1,
  },
  {
    id: "p_tshirt_blanc",
    title: "T-shirt coton épais — Blanc écru",
    description:
      "T-shirt en coton lourd, coupe boxy authentiquement vintage. Un basique intemporel qui vieillit magnifiquement.",
    price: 1800,
    category: "vetements",
    brand: "Petit Bateau",
    country: "FR",
    condition: "Bon état",
    era: "Années 90",
    size: "M",
    measurements: "Poitrine 52 cm · Longueur 68 cm",
    material: "100% coton",
    images: [img("1521572163474-6864f9cf17ab"), img("1583743814966-8936f5b7be1a")],
    tags: ["basique", "coton"],
    status: "AVAILABLE",
    days: 6,
  },
  {
    id: "p_jean_levis",
    title: "Jean brut délavé — Coupe droite",
    description:
      "Jean en denim épais, délavage naturel obtenu au porté. Trouvé dans un dépôt-vente du nord de l'Allemagne.",
    price: 3800,
    category: "vetements",
    brand: "Levi's",
    country: "DE",
    condition: "Bon état",
    era: "Années 90",
    size: "42",
    measurements: "Taille 42 · Entrejambe 78 cm",
    material: "100% coton denim",
    images: [img("1542272604-787c3835535d")],
    tags: ["denim", "jean"],
    status: "SOLD",
    days: 34,
    soldAt: ago(9),
  },
  {
    id: "p_sac_bandouliere_cuir",
    title: "Sac à dos cuir — Cognac vieilli",
    description:
      "Sac à dos en cuir pleine fleur, finitions à la main. Importé de Toscane où il a été fabriqué dans un petit atelier familial.",
    price: 5400,
    compareAtPrice: 7900,
    category: "sacs",
    brand: "Atelier Toscana",
    country: "IT",
    city: "Florence",
    condition: "Comme neuf",
    era: "Années 2000",
    size: "Unique",
    measurements: "40 × 30 × 14 cm",
    material: "Cuir pleine fleur, doublure coton",
    images: [img("1553062407-98eeb64c6a62"), img("1608234807905-4466023792f5")],
    tags: ["cuir", "sac", "italie", "artisanal"],
    status: "AVAILABLE",
    featured: true,
    days: 3,
  },
  {
    id: "p_sac_main_camel",
    title: "Sac à main en cuir — Camel grainé",
    description:
      "Sac à main structuré au cuir grainé, anses renforcées. Une pièce de maroquinerie française qui traverse les saisons.",
    price: 6500,
    category: "sacs",
    brand: "Lancel",
    country: "FR",
    city: "Paris",
    condition: "Très bon état",
    era: "Années 2000",
    size: "Unique",
    measurements: "32 × 22 × 12 cm",
    material: "Cuir de veau grainé",
    images: [img("1584917865442-de89df76afd3")],
    tags: ["sac à main", "cuir", "luxe"],
    status: "AVAILABLE",
    featured: true,
    days: 1,
    hours: 5,
  },
  {
    id: "p_sac_cuir_grane",
    title: "Sac porté épaule — Cuir naturel",
    description:
      "Sac souple en cuir naturel non teint, patine unique. Récupéré dans une boutique de seconde main de Barcelone.",
    price: 4800,
    category: "sacs",
    brand: "Sans marque",
    country: "ES",
    city: "Barcelone",
    condition: "Bon état",
    era: "Années 90",
    size: "Unique",
    measurements: "36 × 26 × 10 cm",
    material: "Cuir de vachette",
    images: [img("1608234807905-4466023792f5"), img("1584917865442-de89df76afd3")],
    tags: ["cuir", "bohème"],
    status: "RESERVED",
    days: 8,
  },
  {
    id: "p_baskets_nike",
    title: "Baskets Nike Air rétro — Rouge/Blanc",
    description:
      "Paire de baskets Nike Air d'époque, semelle d'origine conservée. Nettoyées et désinfectées par nos soins.",
    price: 7500,
    category: "chaussures",
    brand: "Nike",
    country: "DE",
    condition: "Très bon état",
    era: "Années 90",
    size: "43",
    measurements: "Pointure 43 · Semelle 29 cm",
    material: "Cuir et mesh",
    images: [img("1549298916-b41d501d3772"), img("1552346154-21d32810aba3")],
    tags: ["baskets", "sneakers", "nike"],
    status: "AVAILABLE",
    featured: true,
    days: 2,
    hours: 9,
  },
  {
    id: "p_sneakers_retro",
    title: "Sneakers rétro — Multicolore",
    description:
      "Sneakers colorées des années 80, semelle crantée. Un vrai clin d'œil aux rues de Madrid.",
    price: 4200,
    category: "chaussures",
    brand: "Adidas",
    country: "ES",
    condition: "Bon état",
    era: "Années 80",
    size: "42",
    measurements: "Pointure 42",
    material: "Cuir et suède",
    images: [img("1560769629-975ec94e6a86"), img("1460353581641-37baddab0fa2")],
    tags: ["sneakers", "retro"],
    status: "AVAILABLE",
    days: 11,
  },
  {
    id: "p_chaussures_cuir",
    title: "Derbies en cuir — Noir",
    description:
      "Derbies en cuir cousues Blake, fabriquées en Italie. Semelle ressemelée récemment.",
    price: 5900,
    category: "chaussures",
    brand: "Atelier italien",
    country: "IT",
    condition: "Très bon état",
    era: "Années 2000",
    size: "41",
    measurements: "Pointure 41",
    material: "Cuir de veau",
    images: [img("1595950653106-6c9ebd614d3a")],
    tags: ["derbies", "cuir", "formel"],
    status: "AVAILABLE",
    days: 15,
  },
  {
    id: "p_baskets_blanches",
    title: "Baskets blanches minimalistes",
    description:
      "Baskets blanches au design épuré, un classique qui s'accorde avec tout.",
    price: 6800,
    category: "chaussures",
    brand: "Nike",
    country: "FR",
    condition: "Comme neuf",
    era: "Années 2010",
    size: "44",
    measurements: "Pointure 44",
    material: "Cuir lisse",
    images: [img("1560343090-f0409e92791a"), img("1600269452121-4f2416e55c28")],
    tags: ["baskets", "blanc", "minimal"],
    status: "SOLD",
    days: 42,
    soldAt: ago(14),
  },
  {
    id: "p_ours_peluche",
    title: "Ours en peluche ancien — Mohair",
    description:
      "Ours en peluche en mohair, yeux en verre d'origine. Trouvé dans une maison familiale de Bavière.",
    price: 3200,
    category: "jouets",
    brand: "Steiff",
    country: "DE",
    city: "Nuremberg",
    condition: "Vintage patiné",
    era: "Années 60",
    size: "Unique",
    measurements: "Hauteur 34 cm",
    material: "Mohair, rembourrage crin",
    images: [img("1513475382585-d06e58bcb0e0"), img("1558060370-d644479cb6f7")],
    tags: ["peluche", "ancien", "collection"],
    status: "AVAILABLE",
    featured: true,
    days: 4,
  },
  {
    id: "p_voiture_jouet",
    title: "Voiture miniature ancienne — Tôle",
    description:
      "Petite voiture en tôle lithographiée, roues d'origine. Un jouet d'époque qui a traversé les décennies.",
    price: 2600,
    category: "jouets",
    brand: "Jouet ancien",
    country: "FR",
    condition: "Vintage patiné",
    era: "Années 70",
    size: "Unique",
    measurements: "Longueur 18 cm",
    material: "Tôle lithographiée",
    images: [img("1566576912321-d58ddd7a6088")],
    tags: ["jouet", "collection", "retro"],
    status: "AVAILABLE",
    days: 5,
  },
  {
    id: "p_jouets_anciens",
    title: "Lot de jouets anciens en bois",
    description:
      "Ensemble de jouets en bois peints à la main, chinés dans une brocante andalouse.",
    price: 3500,
    category: "jouets",
    brand: "Artisanal",
    country: "ES",
    condition: "Bon état",
    era: "Années 80",
    size: "Unique",
    measurements: "Lot de 6 pièces",
    material: "Bois peint",
    images: [img("1595341888016-a392ef81b7de")],
    tags: ["bois", "enfants", "ancien"],
    status: "SOLD",
    days: 50,
    soldAt: ago(21),
  },
  {
    id: "p_appareil_photo",
    title: "Appareil photo argentique — Reflex 35 mm",
    description:
      "Reflex argentique entièrement révisé, cellule fonctionnelle. Livré avec sa sangle d'origine.",
    price: 12500,
    compareAtPrice: 16000,
    category: "collectibles",
    brand: "Canon",
    country: "DE",
    condition: "Très bon état",
    era: "Années 80",
    size: "Unique",
    measurements: "Boîtier 15 × 10 × 7 cm",
    material: "Alliage et cuir",
    images: [img("1526170375885-4d8ecf77b99f"), img("1558877385-81a1c7e67d72")],
    tags: ["photo", "collection", "vintage"],
    status: "AVAILABLE",
    featured: true,
    days: 2,
    hours: 2,
  },
  {
    id: "p_appareil_vintage",
    title: "Appareil photo vintage — Télémétrique",
    description:
      "Petit appareil télémétrique de collection, objectif lumineux. Pièce rare importée de France.",
    price: 9800,
    category: "collectibles",
    brand: "Olympus",
    country: "FR",
    condition: "Bon état",
    era: "Années 70",
    size: "Unique",
    measurements: "12 × 8 × 6 cm",
    material: "Métal chromé",
    images: [img("1558877385-81a1c7e67d72"), img("1526170375885-4d8ecf77b99f")],
    tags: ["photo", "collection"],
    status: "AVAILABLE",
    days: 9,
  },
  {
    id: "p_montre_vintage",
    title: "Montre vintage — Bracelet cuir",
    description:
      "Montre mécanique remontée à la main, cadran patiné. Révisée par un horloger de Grenade.",
    price: 8500,
    category: "accessoires",
    brand: "Seiko",
    country: "ES",
    city: "Grenade",
    condition: "Très bon état",
    era: "Années 70",
    size: "Unique",
    measurements: "Boîtier 36 mm",
    material: "Acier, cuir",
    images: [img("1523170335258-f5ed11844a49"), img("1524805444758-089113d48a6d")],
    tags: ["montre", "accessoire", "mecanique"],
    status: "AVAILABLE",
    featured: true,
    days: 1,
  },
  {
    id: "p_horloge_ancienne",
    title: "Horloge de table ancienne — Laiton",
    description:
      "Petite horloge de table en laiton poli, mouvement mécanique révisé. Un objet de bureau élégant.",
    price: 7400,
    category: "antiquites",
    brand: "Sans marque",
    country: "FR",
    condition: "Très bon état",
    era: "Années 50",
    size: "Unique",
    measurements: "Hauteur 18 cm",
    material: "Laiton, verre",
    images: [img("1524805444758-089113d48a6d")],
    tags: ["horloge", "antiquite", "laiton"],
    status: "AVAILABLE",
    days: 13,
  },
  {
    id: "p_lunettes_retro",
    title: "Lunettes de soleil rétro — Écaille",
    description:
      "Monture épaisse façon écaille, verres teintés d'origine. Fabriquées en Italie.",
    price: 3900,
    category: "accessoires",
    brand: "Persol",
    country: "IT",
    condition: "Très bon état",
    era: "Années 80",
    size: "Unique",
    measurements: "Verres 52 mm · Branches 145 mm",
    material: "Acétate",
    images: [img("1511499767150-a48a237f0083"), img("1483412033650-1015ddeb83d1")],
    tags: ["lunettes", "soleil", "accessoire"],
    status: "AVAILABLE",
    days: 7,
  },
  {
    id: "p_lunettes_vintage",
    title: "Lunettes vintage — Monture fine dorée",
    description:
      "Monture métal dorée très fine, un accessoire discret et raffiné déniché en Espagne.",
    price: 3400,
    category: "accessoires",
    brand: "Sans marque",
    country: "ES",
    condition: "Bon état",
    era: "Années 90",
    size: "Unique",
    measurements: "Verres 50 mm",
    material: "Métal doré",
    images: [img("1483412033650-1015ddeb83d1")],
    tags: ["lunettes", "dore", "accessoire"],
    status: "SOLD",
    days: 60,
    soldAt: ago(30),
  },
  {
    id: "p_vinyles",
    title: "Lot de vinyles 33 tours — Chanson française",
    description:
      "Sélection de vinyles d'époque, pochettes d'origine conservées. Testés, quelques craquements charmants.",
    price: 4500,
    category: "collectibles",
    brand: "Divers",
    country: "FR",
    condition: "Bon état",
    era: "Années 70",
    size: "Unique",
    measurements: "Lot de 8 disques",
    material: "Vinyle",
    images: [img("1522771739844-6a9f6d5f14af")],
    tags: ["vinyle", "musique", "collection"],
    status: "AVAILABLE",
    days: 10,
  },
  {
    id: "p_vase_ceramique",
    title: "Vase ancien en céramique — Émail crème",
    description:
      "Vase en céramique émaillée, forme élancée. Trouvé dans une maison de Valence, petites traces d'usage en base.",
    price: 5600,
    category: "antiquites",
    brand: "Céramique artisanale",
    country: "ES",
    city: "Valence",
    condition: "Bon état",
    era: "Années 60",
    size: "Unique",
    measurements: "Hauteur 32 cm · Ø 14 cm",
    material: "Céramique émaillée",
    images: [img("1578749556568-bc2c40e68b61")],
    tags: ["vase", "ceramique", "antiquite"],
    status: "AVAILABLE",
    days: 3,
    hours: 14,
  },
  {
    id: "p_deco_vintage",
    title: "Objet de décoration vintage — Forme organique",
    description:
      "Objet décoratif au design organique, chiné aux Pays-Bas. Parfait sur une étagère ou une console.",
    price: 3100,
    category: "decoration",
    brand: "Sans marque",
    country: "NL",
    condition: "Très bon état",
    era: "Années 70",
    size: "Unique",
    measurements: "24 × 16 cm",
    material: "Céramique",
    images: [img("1490312278390-ab64016e0aa9"), img("1513519245088-0e12902e5a38")],
    tags: ["decoration", "interieur"],
    status: "AVAILABLE",
    days: 12,
  },
  {
    id: "p_decoration_ancienne",
    title: "Pièce de décoration ancienne — Cuivre travaillé",
    description:
      "Objet décoratif en cuivre repoussé, patine authentique. Importé de Belgique.",
    price: 6200,
    category: "decoration",
    brand: "Artisanat",
    country: "BE",
    condition: "Vintage patiné",
    era: "Années 50",
    size: "Unique",
    measurements: "Ø 26 cm",
    material: "Cuivre",
    images: [img("1513519245088-0e12902e5a38"), img("1524758631624-e2822e304c36")],
    tags: ["cuivre", "deco", "ancien"],
    status: "RESERVED",
    days: 18,
  },
  {
    id: "p_bijoux_anciens",
    title: "Broche ancienne dorée — Fleur ciselée",
    description:
      "Broche ancienne en métal doré finement ciselée, trouvée dans un marché de Naples.",
    price: 6900,
    category: "trouvailles",
    brand: "Bijou ancien",
    country: "IT",
    city: "Naples",
    condition: "Très bon état",
    era: "Années 60",
    size: "Unique",
    measurements: "Ø 4,5 cm",
    material: "Métal doré, strass",
    images: [img("1515562141207-7a88fb7ce338"), img("1535632066927-ab7c9ab60908")],
    tags: ["bijou", "broche", "trouvaille"],
    status: "AVAILABLE",
    featured: true,
    days: 2,
    hours: 20,
  },
  {
    id: "p_livre_ancien",
    title: "Livre ancien relié — Édition 1954",
    description:
      "Ouvrage relié pleine toile, pages jaunies par le temps. Une pièce de bibliothèque pleine de caractère.",
    price: 2400,
    category: "trouvailles",
    brand: "Éditions anciennes",
    country: "FR",
    condition: "Bon état",
    era: "Années 50",
    size: "Unique",
    measurements: "19 × 13 cm",
    material: "Papier, toile",
    images: [img("1495446815901-a7297e633e8d"), img("1512820790803-83ca734da794")],
    tags: ["livre", "ancien", "collection"],
    status: "AVAILABLE",
    days: 16,
  },
];

export function buildSeedProducts(): Product[] {
  return seedProducts.map(({ days, hours, ...product }) => ({
    ...product,
    quantity: 1 as const,
    createdAt: ago(days, hours ?? 0),
    updatedAt: ago(days, hours ?? 0),
  }));
}

export const DEFAULT_SETTINGS: SiteSettings = {
  siteName: "CABAS DZ",
  logoText: "CABAS DZ",
  logoUrl: "",
  tagline: "Des pièces uniques venues d'Europe.",
  heroTitle: "Chaque pièce raconte une histoire.",
  heroSubtitle: "Découvrez nos trouvailles uniques venues d'Europe.",
  heroImage: img("1441986300917-64674bd600d8", 1400),
  uniqueTitle: "Unique Produit",
  uniqueSubtitle:
    "Une pièce. Un exemplaire. Quand elle part, elle ne revient peut-être jamais.",
  whatsappNumber: "+213 555 12 34 56",
  instagramUrl: "https://instagram.com/cabas.dz",
  facebookUrl: "https://facebook.com/cabasdz",
  tiktokUrl: "https://tiktok.com/@cabas.dz",
  email: "contact@cabasdz.com",
  phone: "+213 555 12 34 56",
  address: "Alger, Algérie",
  deliveryInfo:
    "Livraison partout en Algérie en 24 à 96 h. Paiement à la livraison disponible dans les 58 wilayas. Frais de livraison à partir de 500 DA selon la wilaya.",
  aboutText:
    "CABAS DZ est une boutique algérienne spécialisée dans les pièces uniques d'occasion importées d'Europe. Nous ne vendons pas des stocks : nous vendons des trouvailles.",
  storyText:
    "Tout commence par un cabas vide. De brocante en brocante, de marché aux puces en marché aux puces, nous parcourons la France, l'Allemagne et l'Espagne à la recherche de pièces qui ont une âme. Chaque objet est choisi à la main, nettoyé, vérifié, puis rapporté en Algérie. Ce qui arrive chez nous n'existe qu'en un seul exemplaire — et le jour où il part, il ne revient pas.",
  footerText: "Des pièces uniques venues d'Europe.",
  announcement:
    "🇪🇺 Nouvelle trouvaille chaque semaine · 1 seul exemplaire par produit · Livraison 58 wilayas",
};

export const DEFAULT_ADMIN_USERS: AdminUser[] = [
  {
    id: "admin_1",
    name: "Administrateur CABAS DZ",
    email: "admin@cabasdz.com",
    password: "cabas2026",
    role: "admin",
  },
];

function seedCustomers(): Customer[] {
  const people: Array<Omit<Customer, "id" | "createdAt" | "ordersCount">> = [
    {
      fullName: "Amina Belkacem",
      phone: "+213 661 22 88 41",
      wilaya: "16 - Alger",
      commune: "Hydra",
      address: "14 rue des Frères Bouadou",
    },
    {
      fullName: "Yacine Haddad",
      phone: "+213 770 45 19 07",
      wilaya: "31 - Oran",
      commune: "Bir El Djir",
      address: "Cité 1200 logements, bât. C4",
    },
    {
      fullName: "Nadia Zerrouki",
      phone: "+213 550 71 33 26",
      wilaya: "25 - Constantine",
      commune: "El Khroub",
      address: "Lot 22, rue Ben Badis",
    },
    {
      fullName: "Sofiane Meziane",
      phone: "+213 699 08 54 12",
      wilaya: "19 - Sétif",
      commune: "Sétif",
      address: "12 boulevard de l'ALN",
    },
  ];

  return people.map((person, index) => ({
    ...person,
    id: `cust_${index + 1}`,
    createdAt: ago(30 - index * 6),
    ordersCount: index === 0 ? 2 : 1,
  }));
}

export function createSeedDatabase(): Database {
  const products = buildSeedProducts();
  const customers = seedCustomers();

  const line = (id: string) => {
    const product = products.find((item) => item.id === id)!;
    return {
      productId: product.id,
      title: product.title,
      price: product.price,
      image: product.images[0],
      country: product.country,
      condition: product.condition,
    };
  };

  const orders: Order[] = [
    {
      id: "ord_1",
      reference: `CDZ-${new Date().getFullYear()}-1042`,
      customerId: customers[0].id,
      customerName: customers[0].fullName,
      phone: customers[0].phone,
      wilaya: customers[0].wilaya,
      commune: customers[0].commune,
      address: customers[0].address ?? "",
      note: "Emballage cadeau si possible.",
      items: [line("p_jean_levis")],
      total: products.find((p) => p.id === "p_jean_levis")!.price,
      paymentMethod: "Paiement à la livraison",
      status: "LIVREE",
      createdAt: ago(9, 3),
      updatedAt: ago(6, 1),
    },
    {
      id: "ord_2",
      reference: `CDZ-${new Date().getFullYear()}-1061`,
      customerId: customers[1].id,
      customerName: customers[1].fullName,
      phone: customers[1].phone,
      wilaya: customers[1].wilaya,
      commune: customers[1].commune,
      address: customers[1].address ?? "",
      items: [line("p_baskets_blanches")],
      total: products.find((p) => p.id === "p_baskets_blanches")!.price,
      paymentMethod: "Paiement à la livraison",
      status: "EXPEDIEE",
      createdAt: ago(14, 6),
      updatedAt: ago(12, 2),
    },
    {
      id: "ord_3",
      reference: `CDZ-${new Date().getFullYear()}-1078`,
      customerId: customers[2].id,
      customerName: customers[2].fullName,
      phone: customers[2].phone,
      wilaya: customers[2].wilaya,
      commune: customers[2].commune,
      address: customers[2].address ?? "",
      items: [line("p_jouets_anciens")],
      total: products.find((p) => p.id === "p_jouets_anciens")!.price,
      paymentMethod: "Paiement à la livraison",
      status: "CONFIRMEE",
      createdAt: ago(21, 2),
      updatedAt: ago(20, 4),
    },
    {
      id: "ord_4",
      reference: `CDZ-${new Date().getFullYear()}-1090`,
      customerId: customers[3].id,
      customerName: customers[3].fullName,
      phone: customers[3].phone,
      wilaya: customers[3].wilaya,
      commune: customers[3].commune,
      address: customers[3].address ?? "",
      items: [line("p_lunettes_vintage")],
      total: products.find((p) => p.id === "p_lunettes_vintage")!.price,
      paymentMethod: "Paiement à la livraison",
      status: "NOUVELLE",
      createdAt: ago(30, 1),
      updatedAt: ago(30, 1),
    },
  ];

  return {
    version: 1,
    products,
    orders,
    customers,
    adminUsers: DEFAULT_ADMIN_USERS,
    settings: DEFAULT_SETTINGS,
    mediaAssets: [],
  };
}
